#!/bin/bash
#Author: Alejandro Godofredo Carlstein Ramos Mejia
#Disclaimer: All code is given WITHOUT ANY WARRANTY; 
#            without even the implied warranty of MERCHANTABILITY
#            or FITNESS FOR A PARTICULAR PURPOSE. 
#Version: 1.0.0 

function show_help(){
    echo "List deployments(s) based on environment provided:"
    echo "lsdeploys <environment>"
    echo " >lsdeploys env01"
    echo ""
    echo "Help: "
    echo " >lspods -h"
    echo ""
    echo "Short for:"
    echo "kubectl --namespace=<environment> get deployments"
}


case $1 in
  -h)
    show_help
    ;;
  *)
    case $# in
      1)
        kubectl --namespace=$1 get deployments
        ;;
      *)
       show_help
    esac
esac
