#!/bin/bash
#Author: Alejandro Godofredo Carlstein Ramos Mejia
#Disclaimer: All code is given WITHOUT ANY WARRANTY; 
#            without even the implied warranty of MERCHANTABILITY
#            or FITNESS FOR A PARTICULAR PURPOSE. 
#Version: 1.0.0 

show_help(){
    echo "Show specific configmap based on specific environment:"
    echo "envpod <environment> <configmap name>"
    echo " >showconfigmap env01 pod-name"
    echo ""
    echo "Help: "
    echo "showconfigmap -h"
    echo ""
    echo "Short for:"
    echo " kubectl --namespace=<environment> get configmaps/<pod name> -o=yaml"
}


case $1 in
  -h)
    show_help
    ;;
  *)
    case $# in
      2)
        kubectl --namespace=$1 get configmaps/$2 -o=yaml
        ;;
      *)
        show_help
    esac
esac
